* flashgg

** Introduction
   The basic instructions to setup and run flashgg are described here and in corresponding READMEs 
   in subdirectories of the repository.

   If you get stuck or have questions, please first consult the FAQs page [[https://cms-analysis.github.io/flashgg/][here]].
   
** Setup
   Before you start, **please take note** of these warnings and comments:
   - **N.B.** The setup script will check out many packages and take a while!
   - **N.B.** You can ignore "error: addinfo_cache" lines. 
   - **N.B.** These setup instructions now include the STXS workflow

   Supported releases:
   - (Obsolete) 10_6_1_patch2 required for the STXS stage 1.1 information
   - (Obsolete) 10_6_8 required for the STXS stage 1.2 information
   - 10_6_29 required for full UL analyses (Summer20UL)

   get flashgg:
   #+BEGIN_EXAMPLE
   export SCRAM_ARCH=slc7_amd64_gcc700
   cmsrel CMSSW_10_6_29
   cd CMSSW_10_6_29/src
   cmsenv
   git cms-init
   cd $CMSSW_BASE/src 
   git clone -b microAOD_prod https://github.com/jhosain/flashgg.git 
   source flashgg/setup_flashgg.sh
   #+END_EXAMPLE

   If everything now looks reasonable, you can build:
   #+BEGIN_EXAMPLE
   cd $CMSSW_BASE/src
   scram b -j 4
   #+END_EXAMPLE

** Examples to run on RunII legacy test campaign:
   *Note: copying the proxy file to the working node is not yet supported when using HTCondor as bacth system. Therefore the user must set*
   *the =X509_USER_PROXY= environment variable and run with the =--no-copy-proxy= option*
   #+BEGIN_EXAMPLE
   cd Systematics/test
   voms-proxy-init -voms cms --valid 168:00
   cp /tmp/MYPROXY ~/
   export X509_USER_PROXY=~/MYPROXY
   fggRunJobs.py --load legacy_runII_v1_YEAR.json -d test_legacy_YEAR workspaceStd.py -n 300 -q workday --no-copy-proxy
   #+END_EXAMPLE

   *Note: 2018 workflow is just a skeleton, only scales and smearings are known to be correct.*

** Notes on fggRunJobs.py usage (with HTCondor as batch system):
   *It is highly recommended to run =fggRunJobs.py --help= in order to get a clear picture of the script features*

   To fully exploit the HTCondor cluster logic the fggRunJobs workflow has been reviewed for this specific batch system.
   With other batch system (SGE, LSF, ...) each job is run independently in a single task, with HTCondor instead one cluster
   of jobs is created for each sample (i.e. one cluster for each process specified in the configuration json file).
   The number of jobs in each cluster is determined, as for other system, by fggRunJobs. The user can specify the maximum number
   of jobs for each sample through the =-n= option.

   HTCondor does not allow the user to manually resubmit single jobs within a cluster, jobs are instead resubmitted automatically if the job exit
   code matches a failure condition set by the user (here the user as to be intended as fggRunJobs itself). Currently the fggRunJobs
   consider as failed only jobs for which the cmsRun execution failed and instructs HTCondor to resubmit such jobs up to maximum 3 times
   (this value is hard-coded). Failure in transferring the output ROOT file will not result in a job resubmission since in most cases
   the transfer error is due to lack of disk space and therefore any resubmission will fail as well (the user should clean up the stage out area
   first and then submit new jobs with fggRunJobs). In order to make sure all analysis jobs are processed correctly and no data is
   left behind fggRunJobs keeps an internal bookkeeping of the job that failed even after three automatic resubmission, the user can
   instruct fggRunJobs to resubmit these jobs again by setting the =-m= option to a value greater than 1.
   *Note that it is very unlikely that sporadic failures results in a job fail three consecutive automatic resubmission, so besides increasing*
   *the number of manual resubmission attempts through the =-m= option it is worth investigating deeper the log files to understand the root cause of*
   *the failure.*

   A typical analysis task is summarized below:
   #+BEGIN_EXAMPLE
   voms-proxy-init -voms cms --valid 168:00
   cp /tmp/MYPROXY ~/
   export X509_USER_PROXY=~/MYPROXY
   fggRunJobs.py --load myconfig.json -d outputdir/ cmsrun_cfg.py -n N -q QUEUE --no-copy-proxy
   #+END_EXAMPLE
   By default =-m= is set to 2, this means that each jobs will be retried up to 6 times (3 automatic resubmits by HTCondor * 2 "manual" resubmits
   by fggRunJobs).

   fggRunJobs.py can be left running (e.g. in a screen session) or be killed. The monitoring can be restarted at anytime with:
   #+BEGIN_EXAMPLE
   fggRunJobs.py --load outputdir/config.json --cont
   #+END_EXAMPLE
   If all jobs terminated successfully the script will display a success message, otherwise the monitoring will resume.
   The status of jobs can be also monitored running the standard HTCondor scripts like =condor_q=. fggRunJobs clusters are named "runJobsXX".
   The number of "manual" resubmission can be increase by adding =-m 3= to the above command.
   

** Manual tests:
   And a very basic workflow test (for reference, this is not supposed to give paper-grade results):
   #+BEGIN_EXAMPLE
   cd $CMSSW_BASE/src/flashgg
   cmsRun MicroAOD/test/microAODstd.py processType=sig datasetName=glugluh conditionsJSON=MetaData/data/MetaConditions/Era2016_RR-17Jul2018_v1.json 
   #processType=data/bkg/sig, depending on input file
   #conditionsJSON= add appropriate JSON file for 2016, 2017 or 2018 from MetaData/data/MetaConditions/

   cmsRun Systematics/test/workspaceStd.py processId=ggh_125 doHTXS=1
   #+END_EXAMPLE

   These are just some test examples; the first makes MicroAOD from a MiniAOD file accessed via xrootd, 
   the second produces tag objects and screen output from the new MicroAOD file,
   and the other two process the MicroAOD file to test ntuple and workspace output.

   The setup code will automatically change the initial remote branch's name to upstream to synchronize with the project's old conventions.  
   The code will also automatically create an "origin" repo based on its guess as to where your personal flashgg fork is.
   Check that this has worked correctly if you have trouble pushing.  (See setup_*.sh for what it does.)

* Preparing Crab Job

#+BEGIN_EXAMPLE
cd $CMSSW_BASE/src/flashgg/MetaData/work/
cmsenv
source /cvmfs/cms.cern.ch/crab3/crab.sh
voms-proxy-init -voms cms --valid 168:00
#crab checkwrite --site= <site-name>
./prepareCrabJobs.py -p <parameterSet> -s <jsonFileWithDatasetList> -C <microAODCampaginName> --mkPilot
#+END_EXAMPLE

*** Example for 2018
#+BEGIN_EXAMPLE
./prepareCrabJobs.py -p /afs/cern.ch/user/j/jhossain/Hgg_AC_Analysis/Flashgg/microAOD_prod/CMSSW_10_6_29/src/flashgg/MicroAOD/test/microAODstd.py -s /afs/cern.ch/user/j/jhossain/Hgg_AC_Analysis/Flashgg/microAOD_prod/CMSSW_10_6_29/src/flashgg/MetaData/work/campaigns/GluGluHToGG_MINLO_AC_2018.json --meta-conditions /afs/cern.ch/user/j/jhossain/Hgg_AC_Analysis/Flashgg/microAOD_prod/CMSSW_10_6_29/src/flashgg/MetaData/data/MetaConditions/Era2018_legacy_v1.json --outputPath /store/user/jhossain --outputSite T2_US_Nebraska --lumiMask /eos/user/c/cmsdqm/www/CAF/certification/Collisions18/13TeV/Legacy_2018/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt -C Era2018_legacy_v1_Summer20UL -V v2  --mkPilot
#+END_EXAMPLE

It will produce $CMSSW_BASE/src/flashgg/MetaData/work/Era2018_legacy_v1_Summer20UL dircetory

** Running Crab Job

#+BEGIN_EXAMPLE
cd $CMSSW_BASE/src/flashgg/MetaData/work/Era2018_legacy_v1_Summer20UL
cmsenv
source /cvmfs/cms.cern.ch/crab3/crab.sh
voms-proxy-init -voms cms --valid 168:00
echo crabConfig_*.py | xargs -n 1 crab sub
echo crab_* | xargs -n 1 crab status ## to check the status of the jobs
echo crab_* | xargs -n 1 crab resubmit ## to resubmit failed jobs
OR
echo pilot_*.py | xargs -n 1 crab submit ## it will submit the pilot test crab jobs
OR
crab submit -c crab_*.py
crab status -d ./crab_*
crab report crab_*
#+END_EXAMPLE

*** MINLO MINIAOD Samples for 2016

#+BEGIN_EXAMPLE
“/GluGluHToGGPlusTwoJets_SM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM”,
“/GluGluHToGGPlusTwoJets_MM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM”,
“/GluGluHToGGPlusTwoJets_CPodd_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v2/MINIAODSIM”
#+END_EXAMPLE

 *** LUMI for Legacy_2016

#+BEGIN_EXAMPLE
/eos/user/c/cmsdqm/www/CAF/certification/Collisions16/13TeV/Legacy_2016/Cert_271036-284044_13TeV_Legacy2016_Collisions16_JSON.txt 
#+END_EXAMPLE

***  MINLO MINIAOD Samples for 2016

#+BEGIN_EXAMPLE
“/GluGluHToGGPlusTwoJets_SM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2/MINIAODSIM”,
“/GluGluHToGGPlusTwoJets_MM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2/MINIAODSIM”,
“/GluGluHToGGPlusTwoJets_CPodd_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL16MiniAODAPVv2-106X_mcRun2_asymptotic_preVFP_v11-v2/MINIAODSIM”
#+END_EXAMPLE

***  MINLO MINIAOD Samples for 2017

#+BEGIN_EXAMPLE
“/GluGluHToGGPlusTwoJets_SM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM”,
“/GluGluHToGGPlusTwoJets_MM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM”,
“/GluGluHToGGPlusTwoJets_CPodd_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM”
#+END_EXAMPLE
***  LUMI for Legacy_2017

#+BEGIN_EXAMPLE
/eos/user/c/cmsdqm/www/CAF/certification/Collisions17/13TeV/Legacy_2017/Cert_294927-306462_13TeV_UL2017_Collisions17_GoldenJSON.txt
#+END_EXAMPLE
***  MINLO MINIAOD Samples for 2018

#+BEGIN_EXAMPLE
"/GluGluHToGGPlusTwoJets_SM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM",         	
"/GluGluHToGGPlusTwoJets_CPodd_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM",         	
"/GluGluHToGGPlusTwoJets_MM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/RunIISummer20UL18MiniAODv2-106X_upgrade2018_realistic_v16_L1v1-v2/MINIAODSIM"
#+END_EXAMPLE

*** LUMI for Legacy_2018

#+BEGIN_EXAMPLE
/eos/user/c/cmsdqm/www/CAF/certification/Collisions18/13TeV/Legacy_2018/Cert_314472-325175_13TeV_Legacy2018_Collisions18_JSON.txt
#+END_EXAMPLE

** Copying results from Store

#+BEGIN_EXAMPLE
ssh -XY jhossain@lxplus.cern.ch
voms-proxy-init -voms cms
crab checkwrite --site= <site-name>
xrdfs xrootd-local.unl.edu
ls -l /store/user/jhossain/
ssh -XY jhossain@lxplus.cern.ch
xrdcp root://xrootd-local.unl.edu//store/user/jhossain/Era2017_legacy_v1_Summer20UL/v2/GluGluHToGGPlusTwoJets_SM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/Era2017_legacy_v1_Summer20UL-v2-v0-RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/230302_171839/0000/myMicroAODOutputFile_2.root /afs/cern.ch/user/j/jhossain/public/Hgg_AC_Flashgg/Ntuples_2023
#+END_EXAMPLE

* How to create catalog

#+BEGIN_EXAMPLE
SMYCAMPAIGN import -S ’/MY*FAV*SAMPLE*/*Run3Fall2030*/*’
fggManageSamples.py -C MYCAMPAIGN check -S ’/MY*FAV*SAMPLE*/*Run3Fall2030*/*’
#+END_EXAMPLE

***  OR

#+BEGIN_EXAMPLE
fggManageSamples.py -C MYCAMPAIGN eosimport -S /eos/cms/mypath/
fggManageSamples.py -C MYCAMPAIGN check -S ’/MY*FAV*SAMPLE*/*Run3Fall2030*/*’
#+END_EXAMPLE

***  OR

#+BEGIN_EXAMPLE
fggManageSamples.py -C Era2017_legacy_v1_Summer20UL-v2 -V v0 import
fggManageSamples.py -C Era2017_legacy_v1_Summer20UL-v2 check 
#+END_EXAMPLE

***  OR

#+BEGIN_EXAMPLE
ggManageSamples.py -C Era2017_legacy_v1_Summer20UL_v2 -V v0 import -S /GluGluHToGGPlusTwoJets_SM_M125_TuneCP5_13TeV-amcatnlopowheg-minlo-pythia8/jhossain-Era2017_legacy_v1_Summer20UL-v2-v0-RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2-40c484617c8150a845705b37f7fbbebe/USER

fggManageSamples.py -C Era2017_legacy_v1_Summer20UL_v2 check
#+END_EXAMPLE

**  Get list of campaigns

#+BEGIN_EXAMPLE
fggManageSamples.py -C Era2017_legacy_v1 list raw+grep
#+END_EXAMPLE


