+JobFlavour   = "workday"

+OnExitHold   = ExitStatus != 0 

periodic_release =  (NumJobStarts < 4) && ((CurrentTime - EnteredCurrentStatus) > 60) 

getenv        = True 
input         = /afs/cern.ch/user/j/jhossain/.dasmaps/das_maps_dbs_prod.js 
executable    = test_directory_data/runJobs4.sh
arguments     = $(ProcId)
output        = test_directory_data/runJobs4_$(ClusterId).$(ProcId).out
error         = test_directory_data/runJobs4_$(ClusterId).$(ProcId).err
log           = test_directory_data/runJobs4_$(ClusterId).$(ProcId)_htc.log

RequestCpus   = 1
max_retries   = 2
queue 200 
